//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class carterap
    {
        public carterap()
        {
            this.detalles_pago = new HashSet<detalles_pago>();
            this.fechas_calculo_intereses = new HashSet<fechas_calculo_intereses>();
            this.movimientos = new HashSet<movimientos>();
        }
    
        public int id { get; set; }
        public int vigencia { get; set; }
        public int id_concepto { get; set; }
        public int periodo { get; set; }
        public double valor { get; set; }
        public int id_matricula { get; set; }
        public string id_estudiante { get; set; }
        public double pagado { get; set; }
        public int id_grupo { get; set; }
        public int id_est { get; set; }
        public string estado { get; set; }
        public Nullable<int> pago_genero_intereses { get; set; }
        public Nullable<System.DateTime> fec_reg { get; set; }
        public Nullable<System.DateTime> fec_mod { get; set; }
        public string usu_reg { get; set; }
        public string usu_mod { get; set; }
    
        public virtual conceptos conceptos { get; set; }
        public virtual estudiantes estudiantes { get; set; }
        public virtual grupos_pagos grupos_pagos { get; set; }
        public virtual matriculas matriculas { get; set; }
        public virtual vigencias vigencias { get; set; }
        public virtual ICollection<detalles_pago> detalles_pago { get; set; }
        public virtual ICollection<fechas_calculo_intereses> fechas_calculo_intereses { get; set; }
        public virtual ICollection<movimientos> movimientos { get; set; }
        [NotMapped]
        public double saldo { get { return this.valor-this.pagado;}}
    }
}
