//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class conceptos
    {
        public conceptos()
        {
            this.carterap = new HashSet<carterap>();
            this.config_grupos_pagos = new HashSet<config_grupos_pagos>();
            this.detalles_pago = new HashSet<detalles_pago>();
            this.movimientos = new HashSet<movimientos>();
            this.tarifas = new HashSet<tarifas>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public string estado { get; set; }
        public string cod_contable { get; set; }
    
        public virtual ICollection<carterap> carterap { get; set; }
        public virtual ICollection<config_grupos_pagos> config_grupos_pagos { get; set; }
        public virtual ICollection<detalles_pago> detalles_pago { get; set; }
        public virtual ICollection<movimientos> movimientos { get; set; }
        public virtual ICollection<tarifas> tarifas { get; set; }
    }
}
