//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class config_grupos_pagos
    {
        public int id { get; set; }
        public int id_grupo { get; set; }
        public int id_concepto { get; set; }
        public int vigencia { get; set; }
        public string intereses { get; set; }
        public Nullable<System.DateTime> fec_reg { get; set; }
        public Nullable<System.DateTime> fec_mod { get; set; }
        public string usu_reg { get; set; }
        public string usu_mod { get; set; }
    
        public virtual conceptos conceptos { get; set; }
        public virtual grupos_pagos grupos_pagos { get; set; }
        public virtual vigencias vigencias { get; set; }
    }
}
