//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalles_pago
    {
        public int id { get; set; }
        public int id_pago { get; set; }
        public Nullable<int> id_concepto { get; set; }
        public int periodo { get; set; }
        public int vigencia { get; set; }
        public double valor { get; set; }
        public string tipo { get; set; }
        public int id_cartera { get; set; }
        public string nombre_concepto { get; set; }
    
        public virtual carterap carterap { get; set; }
        public virtual conceptos conceptos { get; set; }
        public virtual pagos pagos { get; set; }
        public virtual vigencias vigencias { get; set; }
    }
}
