//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class documentos
    {
        public int id { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string tipo_documento { get; set; }
        public string descripcion { get; set; }
    
        public virtual tipos_documentos tipos_documentos { get; set; }
    }
}
