//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class estudiantes
    {
        public estudiantes()
        {
            this.carterap = new HashSet<carterap>();
            this.matriculas = new HashSet<matriculas>();
            this.movimientos = new HashSet<movimientos>();
            this.pagos = new HashSet<pagos>();
            this.saldos_a_favor = new HashSet<saldos_a_favor>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_ultima_matricula { get; set; }
        public Nullable<int> id_ultimo_grado { get; set; }
        public string lugar_nacimiento { get; set; }
        public Nullable<System.DateTime> fecha_nacimiento { get; set; }
        public string colegio_procedencia { get; set; }
        public string estado_civil_padres { get; set; }
        public string parentesco_acudiente { get; set; }
        public int id_acudiente { get; set; }
        public Nullable<int> id_tercero_madre { get; set; }
        public Nullable<int> id_tercero_padre { get; set; }
        public int id_tercero_estudiante { get; set; }
        public string identificacion { get; set; }
        public string vive_con { get; set; }
        public string codigo { get; set; }
        public Nullable<System.DateTime> fec_reg { get; set; }
        public Nullable<System.DateTime> fec_mod { get; set; }
        public string usu_reg { get; set; }
        public string usu_mod { get; set; }
    
        public virtual ICollection<carterap> carterap { get; set; }
        public virtual terceros terceros { get; set; }
        public virtual terceros terceros1 { get; set; }
        public virtual terceros terceros2 { get; set; }
        public virtual terceros terceros3 { get; set; }
        public virtual ICollection<matriculas> matriculas { get; set; }
        public virtual ICollection<movimientos> movimientos { get; set; }
        public virtual ICollection<pagos> pagos { get; set; }
        public virtual ICollection<saldos_a_favor> saldos_a_favor { get; set; }
    }
}
