//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class grupos_pagos
    {
        public grupos_pagos()
        {
            this.carterap = new HashSet<carterap>();
            this.config_grupos_pagos = new HashSet<config_grupos_pagos>();
            this.pagos = new HashSet<pagos>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public int prioridad { get; set; }
    
        public virtual ICollection<carterap> carterap { get; set; }
        public virtual ICollection<config_grupos_pagos> config_grupos_pagos { get; set; }
        public virtual ICollection<pagos> pagos { get; set; }
    }
}
