//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class mensajes
    {
        public int id { get; set; }
        public string asunto { get; set; }
        public string mensaje { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string tipo { get; set; }
        public int id_remitente { get; set; }
        public string estado { get; set; }
        public Nullable<int> id_destinatario { get; set; }
    
        public virtual terceros terceros { get; set; }
        public virtual terceros terceros1 { get; set; }
    }
}
