//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class notas_credito
    {
        public notas_credito()
        {
            this.detalles_nota_credito = new HashSet<detalles_nota_credito>();
        }
    
        public int id { get; set; }
        public System.DateTime fecha { get; set; }
        public string estado { get; set; }
        public string id_estudiante { get; set; }
        public int id_grupo { get; set; }
        public int id_est { get; set; }
        public string observacion { get; set; }
        public Nullable<System.DateTime> fec_reg { get; set; }
        public Nullable<System.DateTime> fec_mov { get; set; }
        public string usu_reg { get; set; }
        public string usu_mod { get; set; }
    
        public virtual ICollection<detalles_nota_credito> detalles_nota_credito { get; set; }
        public virtual estudiantes estudiantes { get; set; }
        public virtual grupos_pagos grupos_pagos { get; set; }
    }
}
