//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class periodos
    {
        public int id { get; set; }
        public int periodo { get; set; }
        public string estado { get; set; }
        public int vigencia { get; set; }
        public int vence_dia { get; set; }
    
        public virtual vigencias vigencias { get; set; }
    }
}
