//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class saldos_a_favor
    {
        public int id { get; set; }
        public string id_estudiante { get; set; }
        public double valor { get; set; }
        public string estado { get; set; }
        public System.DateTime fecha { get; set; }
        public int id_est { get; set; }
    
        public virtual estudiantes estudiantes { get; set; }
    }
}
