//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tarifas
    {
        public int id { get; set; }
        public int vigencia { get; set; }
        public int id_grado { get; set; }
        public int id_concepto { get; set; }
        public double valor { get; set; }
        public int periodo_desde { get; set; }
        public int periodo_hasta { get; set; }
    
        public virtual conceptos conceptos { get; set; }
        public virtual grados grados { get; set; }
        public virtual vigencias vigencias { get; set; }
    }
}
