//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class terceros
    {
        public terceros()
        {
            this.detalles_tipos_tercero = new HashSet<detalles_tipos_tercero>();
            this.estudiantes = new HashSet<estudiantes>();
            this.estudiantes1 = new HashSet<estudiantes>();
            this.estudiantes2 = new HashSet<estudiantes>();
            this.estudiantes3 = new HashSet<estudiantes>();
            this.mensajes_acudientes = new HashSet<mensajes_acudientes>();
            this.mensajes = new HashSet<mensajes>();
        }
    
        public int id { get; set; }
        public string identificacion { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string RH { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public string celular { get; set; }
        public string email { get; set; }
        public string tipo_identificacion { get; set; }
        public string ocupacion { get; set; }
        public string direccion_trabajo { get; set; }
        public string sexo { get; set; }
    
        public virtual ICollection<detalles_tipos_tercero> detalles_tipos_tercero { get; set; }
        public virtual ICollection<estudiantes> estudiantes { get; set; }
        public virtual ICollection<estudiantes> estudiantes1 { get; set; }
        public virtual ICollection<estudiantes> estudiantes2 { get; set; }
        public virtual ICollection<estudiantes> estudiantes3 { get; set; }
        public virtual ICollection<mensajes_acudientes> mensajes_acudientes { get; set; }
        public virtual ICollection<mensajes> mensajes { get; set; }
    }
}
