//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipos_documentos
    {
        public tipos_documentos()
        {
            this.documentos = new HashSet<documentos>();
            this.movimientos = new HashSet<movimientos>();
        }
    
        public string id { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<documentos> documentos { get; set; }
        public virtual ICollection<movimientos> movimientos { get; set; }
    }
}
