//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipos_terceros
    {
        public tipos_terceros()
        {
            this.detalles_tipos_tercero = new HashSet<detalles_tipos_tercero>();
        }
    
        public string nombre { get; set; }
    
        public virtual ICollection<detalles_tipos_tercero> detalles_tipos_tercero { get; set; }
    }
}
