//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vigencias
    {
        public vigencias()
        {
            this.carterap = new HashSet<carterap>();
            this.config_grupos_pagos = new HashSet<config_grupos_pagos>();
            this.detalles_pago = new HashSet<detalles_pago>();
            this.intereses_manuales = new HashSet<intereses_manuales>();
            this.matriculas = new HashSet<matriculas>();
            this.movimientos = new HashSet<movimientos>();
            this.parametros = new HashSet<parametros>();
            this.periodos = new HashSet<periodos>();
            this.tarifas = new HashSet<tarifas>();
            this.detalles_nota_credito = new HashSet<detalles_nota_credito>();
        }
    
        public int vigencia { get; set; }
        public string estado { get; set; }
        public Nullable<System.DateTime> fec_reg { get; set; }
        public Nullable<System.DateTime> fec_mod { get; set; }
        public string usu_reg { get; set; }
        public string usu_mod { get; set; }
    
        public virtual ICollection<carterap> carterap { get; set; }
        public virtual ICollection<config_grupos_pagos> config_grupos_pagos { get; set; }
        public virtual ICollection<detalles_pago> detalles_pago { get; set; }
        public virtual ICollection<intereses_manuales> intereses_manuales { get; set; }
        public virtual ICollection<matriculas> matriculas { get; set; }
        public virtual ICollection<movimientos> movimientos { get; set; }
        public virtual ICollection<parametros> parametros { get; set; }
        public virtual ICollection<periodos> periodos { get; set; }
        public virtual ICollection<tarifas> tarifas { get; set; }
        public virtual ICollection<detalles_nota_credito> detalles_nota_credito { get; set; }
    }
}
